<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-C7JRHPB" failures="1" tests="2" name="Test" time="21.742" errors="0" timestamp="2024-11-27T19:50:17 IST">
  <testcase classname="DataProvider.DP" name="logintest" time="17.674"/>
  <testcase classname="DataProvider.DP" name="logintest" time="21.643">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at DataProvider.DP.logintest(DP.java:40)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1575)
... Removed 11 stack frames]]>
    </failure>
  </testcase> <!-- logintest -->
</testsuite> <!-- Test -->
